<?php

/**
 * @file
 * Adds the javascript need to search the sites content.
 */

include_once 'loop_search_node_settings.features.inc';

/**
 * Implements hook_search_node_page_configuration_alter().
 *
 * Add or between types in the type "filter".
 */
function loop_search_node_settings_search_node_page_configuration_alter(&$conf, $configuration) {
  $conf['provider']['filters']['taxonomy'][] = [
    'field' => 'type',
    'name' => 'Type',
    'type' => 'or',
    'terms' => [
      'external_sources' => [
        'value' => 'external_sources',
      ],
      'loop_documents_document' => [
        'value' => 'loop_documents_document',
      ],
      'loop_documents_collection' => [
        'value' => 'loop_documents_collection',
      ],
      'post' => [
        'value' => 'post',
      ],
    ],
  ];
}
