<?php

/**
 * @file
 * Install hooks for Loop permissions.
 */

/**
 * Implements hook_install().
 */
function loop_permissions_install() {
  db_insert('node_limit')
    ->fields([
      'lid' => 1,
      'nlimit' => 0,
      'title' => 'Disable read only role content creation',
      'weight' => 0,
    ])
    ->execute();

  db_insert('node_limit_role')
    ->fields([
      'lid' => 1,
      'rid' => 6,
    ])
    ->execute();
}
