<?php

/**
 * @file
 * Add Siteimprove functionality and js.
 */

/**
 * Implements hook_menu().
 */
function itk_siteimprove_menu() {
  $items = array();

  $items['admin/config/system/itk-siteimprove'] = array(
    'title' => 'ITK Siteimprove',
    'description' => 'Manage ITK Siteimprove settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('itk_siteimprove_form'),
    'access arguments' => array('administer itk siteimprove'),
  );

  return $items;
}

/**
 * Add new permission.
 *
 * @return array
 *   An array defining a permission.
 */
function itk_siteimprove_permission() {
  return array(
    'administer itk siteimprove' => array(
      'title' => t('Administer ITK Siteimprove module'),
      'description' => t('Perform administration tasks related to ITK Siteimprove.'),
    ),
  );
}

/**
 * Custom form for configuring ITK Siteimprove.
 *
 * @param array $form
 *   Custom configuration form.
 * @param array $form_state
 *   Form state of custom form.
 *
 * @return mixed
 *   The complete form.
 */
function itk_siteimprove_form(array $form, array &$form_state) {
  $form = [];
  $form['tabs'] = [
    '#type' => 'vertical_tabs',
  ];
  $form['general'] = [
    '#type' => 'details',
    '#title' => t('General settings'),
    '#group' => 'tabs',
  ];
  $form['general']['itk_siteimprove_key'] = [
    '#type' => 'textfield',
    '#title' => t('Siteimprove key'),
    '#required' => TRUE,
    '#default_value' => variable_get('itk_siteimprove_key', ''),
  ];
  $form['general']['itk_siteimprove_excludes'] = [
    '#type' => 'textarea',
    '#title' => t('Path excludes'),
    '#description' => t('For example admin/*'),
    '#required' => FALSE,
    '#default_value' => variable_get('itk_siteimprove_excludes', 'admin/*'),
  ];
  $form['cookieinformation'] = [
    '#type' => 'details',
    '#title' => t('Cookieinformation.com'),
    '#group' => 'tabs',
  ];
  $form['cookieinformation']['itk_use_cookieinformation'] = [
    '#type' => 'checkbox',
    '#title' => t('Check this if the site uses cookieinformation.com'),
    '#required' => FALSE,
    '#default_value' => variable_get('itk_use_cookieinformation', FALSE),
  ];

  return system_settings_form($form);
}

/**
 * Implements hook_preprocess_page().
 *
 * Add script if all conditions pass.
 */
function itk_siteimprove_preprocess_page(&$variables) {
  $key = variable_get('itk_siteimprove_key', '');
  $use_cookie_information = variable_get('itk_use_cookieinformation', '');

  // Ignore if key is not set.
  if (!$key) {
    return;
  }

  // Check for excludes.
  $excludePatterns = explode("\r\n", variable_get('itk_siteimprove_excludes', []));

  $trackPath = TRUE;
  $currentPath = current_path();

  // Check each exclude pattern.
  foreach ($excludePatterns as $pattern) {
    if (drupal_match_path($currentPath, $pattern)) {
      $trackPath = FALSE;
      break;
    }
  }

  // Inject script if allowed path.
  if ($trackPath) {
    drupal_add_js(drupal_get_path('module', 'itk_siteimprove') . '/js/itk-siteimprove.js', 'file');
    drupal_add_js(array(
      'itk_siteimprove' => array(
        'key' => $key,
        'useCookieinformation' => boolval($use_cookie_information),
      ),
    ), 'setting');
  }
}
